pipeline {
    agent any
    stages {
            stage('clone'){
                steps{
                    echo 'Cloning git repository'
                }
            }
            stage('build'){
                steps{
                    echo 'Building image from code'
                    echo 'Build successfull'
                }
            }
            stage('push'){
                steps{
                    echo 'Pushing to docker hub'
                    echo 'Push successfull'
                }
            }
        }
}
