apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudvault-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cloudvault   
  endpoints:
    - port: metrics    
      path: /metrics
      interval: 10s
